### ISSUE TITLE
Iter 4  - Manager, table and design

### ISSUE THREAD

**Issue by navacohen90** [navacohen90/Click-a-Table#10]
##### Related User Stories:

US4
#### Checklist, e.g.,:
- [ ] Feature scenarios/tests passing
- [ ] Iteration page updated, including:
  - [ ] Iteration retrospective
  - [ ] Client review
  - [ ] Issues updates
  - [ ] Section on application of course materials
- [ ] git tag
- [ ] Next iteration:
  - [ ] Open page
  - [ ] Select stories and plan issues
  - [ ] Test scenarios
- [ ] All engineers filled peer-review 
- [ ] Submitted
  - [ ] Announcement in chat room
  - [ ] Assign this issue to checker
  - [ ] Register for a review meeting

**Comment by sarah-hoter** [comment]
@hadarp please check

**Comment by hadarp** [comment]
Checked
