### ISSUE TITLE
interation 3 -https://github.com/navacohen90/Click-a-Table/wiki/iter-3-Design-and-invoice

### ISSUE THREAD

**Issue by yafitha** [navacohen90/Click-a-Table#102]
Todo: delete all unnecessary text, add suitable labels (with priotity and estimation), milestone, assignee
#### Related Issues/Tasks
- [ ] #1
- [ ] #2
#### Scenario (test)
- [ ] Step 1
- [ ] ...
- [ ] Expected result
## User Story Template
- As a ...
- I want ...
- So that ...
#### Checklist, e.g.,:
- [ ] Feature scenarios/tests passing
- [ ] Iteration page updated, including:
  - [ ] Iteration retrospective
  - [ ] Client review
  - [ ] Issues updates
  - [ ] Section on application of course materials
- [ ] git tag
- [ ] Next iteration:
  - [ ] Open page
  - [ ] Select stories and plan issues
  - [ ] Test scenarios
- [ ] All engineers filled peer-review 
- [ ] Submitted
  - [ ] Announcement in chat room
  - [ ] Assign this issue to checker
  - [ ] Register for a review meeting

**Comment by sarah-hoter** [comment]
קיים כבר, מיותר
