### ISSUE TITLE
project4-sds-submission

### ISSUE THREAD

**Issue by navacohen90** [navacohen90/Click-a-Table#3]
פרויקט 4 – מפרט תיכון תוכנה (SDS)
להלן קישור לקובץ:
https://github.com/navacohen90/Click-a-Table/wiki/sds

**Comment by robi-y** [comment]
whats in there?

**Comment by sarah-hoter** [comment]
now finished

**Comment by hadarp** [comment]
Checked, SDS Review Summary missing.

**Comment by sarah-hoter** [comment]
לא היה סקר על ה-sds
הגשת התרגיל נדחתה ביומיים, ולכן לא היו סקרים
גם בדף הפגישות אין רישום לזה

**Comment by navacohen90** [comment]
@hadarp 
לא היה סקר על ה-sds
הגשת התרגיל נדחתה ביומיים, ולכן לא היו סקרים
גם בדף הפגישות אין רישום לזה
