### ISSUE TITLE
Iter 1 - menu view and courses order

### ISSUE THREAD

**Issue by navacohen90** [navacohen90/Click-a-Table#7]
##### Related User Stories:

US4
#### Checklist, e.g.,:
- [x] Feature scenarios/tests passing
- [x] Iteration page updated, including:
  - [x] Iteration retrospective
  - [x] Client review
  - [x] Issues updates
  - [x] Section on application of course materials
- [x] git tag
- [x] Next iteration:
  - [x] Open page
  - [x] Select stories and plan issues
  - [x] Test scenarios
- [x] All engineers filled peer-review 
- [x] Submitted
  - [x] Announcement in chat room
  - [x] Assign this issue to checker
  - [x] Register for a review meeting

**Comment by navacohen90** [comment]
@hadarp done

**Comment by hadarp** [comment]
checked
